[package]
name = "smallclap"
version = "0.1.0"
authors = ["Jitu Das <jitudas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallclap_derive = { path = "./smallclap_derive" }